#include <stdio.h>
#include <stdlib.h>

int
get_opcode_bytelen(unsigned char *buf, int pc)
{
	int bytes = 1;
	printf("%04x ", pc);
	unsigned char *opcode = &buf[pc];
	switch (*opcode) {
		case 0x00: printf("NOP "); break;
		case 0x01: printf("LXI B<-%02x C<-%02x", *(opcode + 1), *(opcode + 2)); bytes = 3; break;
		case 0x02: printf("NOP"); break;
		case 0x03: printf("NOP"); break;
		case 0x04: printf("NOP"); break;
		case 0x05: printf("NOP"); break;
		case 0x06: printf("NOP"); break;
		case 0x07: printf("NOP"); break;
		case 0x08: printf("NOP"); break;
		case 0x09: printf("NOP"); break;
		case 0x0a: printf("NOP"); break;
		case 0x0b: printf("NOP"); break;
		case 0x0c: printf("NOP"); break;
		case 0x0d: printf("NOP"); break;
		case 0x0e: printf("NOP"); break;
		case 0x0f: printf("NOP"); break;
		case 0x10: printf("NOP"); break;
		case 0x11: printf("NOP"); break;
		case 0x12: printf("NOP"); break;
		case 0x13: printf("NOP"); break;
		case 0x14: printf("NOP"); break;
		case 0x15: printf("NOP"); break;
		case 0x16: printf("NOP"); break;
		case 0x17: printf("NOP"); break;
		case 0x18: printf("NOP"); break;
		case 0x19: printf("NOP"); break;
		case 0x1a: printf("NOP"); break;
		case 0x1b: printf("NOP"); break;
		case 0x1c: printf("NOP"); break;
		case 0x1d: printf("NOP"); break;
		case 0x1e: printf("NOP"); break;
		case 0x1f: printf("NOP"); break;
		case 0x20: printf("NOP"); break;
		case 0x21: printf("NOP"); break;
		case 0x22: printf("NOP"); break;
		case 0x23: printf("NOP"); break;
		case 0x24: printf("NOP"); break;
		case 0x25: printf("NOP"); break;
		case 0x26: printf("NOP"); break;
		case 0x27: printf("NOP"); break;
		case 0x28: printf("NOP"); break;
		case 0x29: printf("NOP"); break;
		case 0x2a: printf("NOP"); break;
		case 0x2b: printf("NOP"); break;
		case 0x2c: printf("NOP"); break;
		case 0x2d: printf("NOP"); break;
		case 0x2e: printf("NOP"); break;
		case 0x2f: printf("NOP"); break;
		case 0x30: printf("NOP"); break;
		case 0x31: printf("NOP"); break;
		case 0x32: printf("NOP"); break;
		case 0x33: printf("NOP"); break;
		case 0x34: printf("NOP"); break;
		case 0x35: printf("NOP"); break;
		case 0x36: printf("NOP"); break;
		case 0x37: printf("NOP"); break;
		case 0x38: printf("NOP"); break;
		case 0x39: printf("NOP"); break;
		case 0x3a: printf("NOP"); break;
		case 0x3b: printf("NOP"); break;
		case 0x3c: printf("NOP"); break;
		case 0x3d: printf("NOP"); break;
		case 0x3e: printf("NOP"); break;
		case 0x3f: printf("NOP"); break;
		case 0x40: printf("NOP"); break;
		case 0x41: printf("NOP"); break;
		case 0x42: printf("NOP"); break;
		case 0x43: printf("NOP"); break;
		case 0x44: printf("NOP"); break;
		case 0x45: printf("NOP"); break;
		case 0x46: printf("NOP"); break;
		case 0x47: printf("NOP"); break;
		case 0x48: printf("NOP"); break;
		case 0x49: printf("NOP"); break;
		case 0x4a: printf("NOP"); break;
		case 0x4b: printf("NOP"); break;
		case 0x4c: printf("NOP"); break;
		case 0x4d: printf("NOP"); break;
		case 0x4e: printf("NOP"); break;
		case 0x4f: printf("NOP"); break;
		case 0x50: printf("NOP"); break;
		case 0x51: printf("NOP"); break;
		case 0x52: printf("NOP"); break;
		case 0x53: printf("NOP"); break;
		case 0x54: printf("NOP"); break;
		case 0x55: printf("NOP"); break;
		case 0x56: printf("NOP"); break;
		case 0x57: printf("NOP"); break;
		case 0x58: printf("NOP"); break;
		case 0x59: printf("NOP"); break;
		case 0x5a: printf("NOP"); break;
		case 0x5b: printf("NOP"); break;
		case 0x5c: printf("NOP"); break;
		case 0x5d: printf("NOP"); break;
		case 0x5e: printf("NOP"); break;
		case 0x5f: printf("NOP"); break;
		case 0x60: printf("NOP"); break;
		case 0x61: printf("NOP"); break;
		case 0x62: printf("NOP"); break;
		case 0x63: printf("NOP"); break;
		case 0x64: printf("NOP"); break;
		case 0x65: printf("NOP"); break;
		case 0x66: printf("NOP"); break;
		case 0x67: printf("NOP"); break;
		case 0x68: printf("NOP"); break;
		case 0x69: printf("NOP"); break;
		case 0x6a: printf("NOP"); break;
		case 0x6b: printf("NOP"); break;
		case 0x6c: printf("NOP"); break;
		case 0x6d: printf("NOP"); break;
		case 0x6e: printf("NOP"); break;
		case 0x6f: printf("NOP"); break;
		case 0x70: printf("NOP"); break;
		case 0x71: printf("NOP"); break;
		case 0x72: printf("NOP"); break;
		case 0x73: printf("NOP"); break;
		case 0x74: printf("NOP"); break;
		case 0x75: printf("NOP"); break;
		case 0x76: printf("NOP"); break;
		case 0x77: printf("NOP"); break;
		case 0x78: printf("NOP"); break;
		case 0x79: printf("NOP"); break;
		case 0x7a: printf("NOP"); break;
		case 0x7b: printf("NOP"); break;
		case 0x7c: printf("NOP"); break;
		case 0x7d: printf("NOP"); break;
		case 0x7e: printf("NOP"); break;
		case 0x7f: printf("NOP"); break;
		case 0x80: printf("NOP"); break;
		case 0x81: printf("NOP"); break;
		case 0x82: printf("NOP"); break;
		case 0x83: printf("NOP"); break;
		case 0x84: printf("NOP"); break;
		case 0x85: printf("NOP"); break;
		case 0x86: printf("NOP"); break;
		case 0x87: printf("NOP"); break;
		case 0x88: printf("NOP"); break;
		case 0x89: printf("NOP"); break;
		case 0x8a: printf("NOP"); break;
		case 0x8b: printf("NOP"); break;
		case 0x8c: printf("NOP"); break;
		case 0x8d: printf("NOP"); break;
		case 0x8e: printf("NOP"); break;
		case 0x8f: printf("NOP"); break;
		case 0x90: printf("NOP"); break;
		case 0x91: printf("NOP"); break;
		case 0x92: printf("NOP"); break;
		case 0x93: printf("NOP"); break;
		case 0x94: printf("NOP"); break;
		case 0x95: printf("NOP"); break;
		case 0x96: printf("NOP"); break;
		case 0x97: printf("NOP"); break;
		case 0x98: printf("NOP"); break;
		case 0x99: printf("NOP"); break;
		case 0x9a: printf("NOP"); break;
		case 0x9b: printf("NOP"); break;
		case 0x9c: printf("NOP"); break;
		case 0x9d: printf("NOP"); break;
		case 0x9e: printf("NOP"); break;
		case 0x9f: printf("NOP"); break;
		case 0xa0: printf("NOP"); break;
		case 0xa1: printf("NOP"); break;
		case 0xa2: printf("NOP"); break;
		case 0xa3: printf("NOP"); break;
		case 0xa4: printf("NOP"); break;
		case 0xa5: printf("NOP"); break;
		case 0xa6: printf("NOP"); break;
		case 0xa7: printf("NOP"); break;
		case 0xa8: printf("NOP"); break;
		case 0xa9: printf("NOP"); break;
		case 0xaa: printf("NOP"); break;
		case 0xab: printf("NOP"); break;
		case 0xac: printf("NOP"); break;
		case 0xad: printf("NOP"); break;
		case 0xae: printf("NOP"); break;
		case 0xaf: printf("NOP"); break;
		case 0xb0: printf("NOP"); break;
		case 0xb1: printf("NOP"); break;
		case 0xb2: printf("NOP"); break;
		case 0xb3: printf("NOP"); break;
		case 0xb4: printf("NOP"); break;
		case 0xb5: printf("NOP"); break;
		case 0xb6: printf("NOP"); break;
		case 0xb7: printf("NOP"); break;
		case 0xb8: printf("NOP"); break;
		case 0xb9: printf("NOP"); break;
		case 0xba: printf("NOP"); break;
		case 0xbb: printf("NOP"); break;
		case 0xbc: printf("NOP"); break;
		case 0xbd: printf("NOP"); break;
		case 0xbe: printf("NOP"); break;
		case 0xbf: printf("NOP"); break;
		case 0xc0: printf("NOP"); break;
		case 0xc1: printf("NOP"); break;
		case 0xc2: printf("NOP"); break;
		case 0xc3: printf("NOP"); break;
		case 0xc4: printf("NOP"); break;
		case 0xc5: printf("NOP"); break;
		case 0xc6: printf("NOP"); break;
		case 0xc7: printf("NOP"); break;
		case 0xc8: printf("NOP"); break;
		case 0xc9: printf("NOP"); break;
		case 0xca: printf("NOP"); break;
		case 0xcb: printf("NOP"); break;
		case 0xcc: printf("NOP"); break;
	}

	printf("\n");
	return bytes;
}

int
main(void) {
	FILE *f = fopen("space-invaders.rom", "r");
	if (f == NULL) {
		perror("failed to open rom");
	}

	fseek(f, 0, SEEK_END);
	long len = ftell(f);
	fseek(f, 0, SEEK_SET);

	unsigned char *buf = malloc(len);
	fread(buf, sizeof(unsigned char), len, f);
	fclose(f);
	int pc = 0;

	while (pc < len) {
		pc += get_opcode_bytelen(buf, pc);
	}

	return 0;
}
